# Generated by Django 6.0.5 on 2026-06-04 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_token_hash', models.CharField(max_length=128, unique=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(default='Villager', max_length=32)),
                ('name_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('mute_reason', models.CharField(blank=True, max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
                ('severe_filter_hits', models.PositiveIntegerField(default=0)),
                ('last_filter_hit_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agora identities',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('body_original', models.TextField(max_length=500)),
                ('body_clean', models.TextField(max_length=700)),
                ('was_filtered', models.BooleanField(default=False)),
                ('filter_hits', models.JSONField(blank=True, default=list)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=255)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='agora.agoraidentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agora_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agora_chatm_created_fd275c_idx'), models.Index(fields=['ip_hash', '-created_at'], name='agora_chatm_ip_hash_51cf4e_idx')],
            },
        ),
    ]
