# Generated by Django 6.0.5 on 2026-06-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField()),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('goal_label', models.CharField(blank=True, max_length=80)),
                ('goal_text', models.CharField(blank=True, max_length=255)),
                ('goal_icon', models.CharField(blank=True, max_length=255)),
                ('meta', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['major_god__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MajorGod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('focus', models.CharField(blank=True, max_length=160)),
                ('bonuses', models.JSONField(blank=True, default=list)),
                ('portrait', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('hud_ring', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['pantheon__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pantheon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('background', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('time', models.CharField(blank=True, max_length=24)),
                ('population', models.CharField(blank=True, max_length=24)),
                ('action', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('phase', models.CharField(blank=True, max_length=80)),
                ('food', models.PositiveIntegerField(default=0)),
                ('wood', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('favor', models.PositiveIntegerField(default=0)),
                ('build_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='builds.buildorder')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='buildorder',
            name='major_god',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_orders', to='builds.majorgod'),
        ),
        migrations.AddField(
            model_name='majorgod',
            name='pantheon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_gods', to='builds.pantheon'),
        ),
        migrations.AlterUniqueTogether(
            name='buildorder',
            unique_together={('major_god', 'slug')},
        ),
    ]
