# Generated by Django 6.0.5 on 2026-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildorderstep',
            old_name='phase',
            new_name='pop',
        ),
        migrations.RenameField(
            model_name='buildorderstep',
            old_name='population',
            new_name='split_pop',
        ),
        migrations.RenameField(
            model_name='majorgod',
            old_name='icon',
            new_name='breakout_portrait',
        ),
        migrations.RenameField(
            model_name='pantheon',
            old_name='image',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='buildorder',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pantheon',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='buildorder',
            name='portrait',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='split_favor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='split_food',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='split_gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='split_wood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildorderstep',
            name='type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='majorgod',
            name='subtitle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='pantheon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='buildorder',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buildorderstep',
            name='favor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='buildorderstep',
            name='food',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='buildorderstep',
            name='gold',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='buildorderstep',
            name='wood',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
